### ISSUE TITLE
ArgumentOutOfRangeException retrieving NEO from 17Lands

### ISSUE THREAD

**Issue by leidolf** [LazarQt/LimitedPower.DraftHelperSync#2]
Default config for NEO retrieving 17Lands data, receive the following error message:

Synced data for: The Modern Age
Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at LimitedPower.DraftHelperSync.Extensions.MtgaHelperCardExtensions.GetCard(List`1 mtgaHelperCards, String cardName, String set) in C:\dev\LimitedPower.DraftHelperSync\LimitedPower.DraftHelperSync\Extensions\MtgaHelperCardExtensions.cs:line 20
   at LimitedPower.DraftHelperSync.Program.Main() in C:\dev\LimitedPower.DraftHelperSync\LimitedPower.DraftHelperSync\Program.cs:line 173

**Comment by LazarQt** [comment]
Can you try again with the new version here: https://github.com/LazarQt/LimitedPower.DraftHelperSync/releases/tag/0.2.1

**Comment by leidolf** [comment]
It completes successfully now, thank you!  FYI, that download file has an extra .DraftHelperSync extension and there is an extra MtgahelperSync subfolder inside.

**Comment by LazarQt** [comment]
Oh woops, my bad! Will remove it and create a new release but seems your issue is fixed. Have fun!
