### ISSUE TITLE
OutOfRangeException for new set BRO

### ISSUE THREAD

**Issue by roofling** [LazarQt/LimitedPower.DraftHelperSync#6]
Trying to run the sync with the new set Brothers' War produces another error.

Application: LimitedPower.DraftHelperSync.exe
CoreCLR Version: 5.0.1722.21314
.NET Version: 5.0.17
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at LimitedPower.DraftHelperSync.Extensions.MtgaHelperCardExtensions.GetCard(List`1 mtgaHelperCards, String cardName, String set) in C:\dev\LimitedPower.DraftHelperSync\LimitedPower.DraftHelperSync\Extensions\MtgaHelperCardExtensions.cs:line 23
   at LimitedPower.DraftHelperSync.Program.Main() in C:\dev\LimitedPower.DraftHelperSync\LimitedPower.DraftHelperSync\Program.cs:line 130

![BRO set download](https://user-images.githubusercontent.com/111249780/202935853-13521863-e3fd-487d-8e16-9872de27a773.png)

**Comment by LazarQt** [comment]
Can you conform that it works with latest release https://github.com/LazarQt/LimitedPower.DraftHelperSync/releases/tag/1.1.4 ?

**Comment by roofling** [comment]
Yep the new version works now. Completes with no issues.

**Comment by LazarQt** [comment]
Glad to hear, thanks for your feedback 👍
